# Generated by Django 5.1.5 on 2025-02-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mane', models.CharField(max_length=100)),
                ('price', models.PositiveBigIntegerField()),
                ('desc', models.TextField()),
                ('pic', models.ImageField(upload_to='products/')),
                ('stock', models.PositiveBigIntegerField(default=1)),
            ],
        ),
    ]
