# Generated by Django 5.1.5 on 2025-02-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mane',
            new_name='name',
        ),
    ]
